<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginDataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>693851fb-3427-4e64-a1c1-915afca619ce</testSuiteGuid>
   <testCaseLink>
      <guid>c88c5462-849c-4f70-b404-823a4d4dc822</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC 1.01 Login(success DataDrivenTesting)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0663b3a9-cfad-4c76-a0b5-6c440620468c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0663b3a9-cfad-4c76-a0b5-6c440620468c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>afe1add2-4273-438e-9c7b-4acc6db563da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0663b3a9-cfad-4c76-a0b5-6c440620468c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fdfddc2f-1f58-48ae-8aea-7d0ee0542f19</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
